### ISSUE TITLE
Replicate Log Entries #9

### ISSUE THREAD

**Issue by ozgen** [ozgen/jraft#10]
**Description:** Implement the logic for log replication from the leader to the followers.

**Tasks:**

- [x] Add a method to the Node class for log replication.
- [x] Determine the prefix and suffix of log entries to be sent to followers.
- [x] Send LogRequest messages to the followers with the necessary log information.
- [ ] Write tests to ensure the correct replication of log entries.
